# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Aaron Councilman
title: PhD Student
email: aaronjc4@illinois.edu
# website: www.github.com/counc009

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  counc009
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: aaron-councilman-910847149
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-3871-8523

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Aaron and I'm a PhD student and research assistant at the University of Illinois Urbana-Champaign. I'm working in Professor Vikram Adve's group, on program synthesis for domain-specific languages. I'm also interested in compilers and programming languages for heterogenous parallel programming and have research experience in parallel programming and extensible languages.

  My primary interests are: <mark>automata theory</mark>, <mark>program synthesis</mark>, and <mark>programming languages</mark>.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: University of Illinois-Urbana Champaign
        caption: 2021-Present
        sub_title: PhD Computer Science
        # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #  During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #  I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

      - layout: top-middle
        title: University of Minnesota-Twin Cities
        caption: 2017-2021
        sub_title: BS Computer Science, summa cum laude

  - title: Research
    layout: list
    content:
     - layout: top-middle
       title: Verified LLM-Generated Code
       caption: 2025
       description: |
         **Aaron Councilman**, David Fu, Aryan Gupta, Chengxiao Wang, David
         Grove, Yu-Xiong Wang, Vikram Adve. 2025. *Towards Formal Verification
         of LLM-Generated Code from Natural Language Prompts*.
         [arXiv:2507.13290](https://arxiv.org/abs/2507.13290).

     - layout: top-middle
       title: Hardware-Agnostic Programming of Heterogeneous Systems
       description: |
         <h2 style="text-align: center;">Hercules</h2>
         2025 <br>
         [gitlab.engr.illinois.edu/llvm/hercules](https://gitlab.engr.illinois.edu/llvm/hercules)

         Russel Arbore, **Aaron Councilman**, Xavier Routh, Ryan Ziegler,
         Praneet Rathi, Vikram Adve. 2025. *Hercules: A Compiler for
         Productive Programming of Heterogeneous Systems*.
         [arXiv:2503.10855](https://arxiv.org/abs/2503.10855).

         <h2 style="text-align: center;">HPVM</h2>
         2022 <br>
         [gitlab.engr.illinois.edu/llvm/hpvm-release](https://gitlab.engr.illinois.edu/llvm/hpvm-release)

         Adel Ejjeh, **Aaron Councilman**, Akash Kothari, Maria Kotsifakou,
         Leon Medvinsky, Abdul Rafae Noor, Hashim Sharif, Yifan Zhao, Sarita
         Adve, Sasa Misailovic, Vikram Adve. 2022. *HPVM: Hardware-Agnostic
         Programming for Heterogeneous Parallel Systems*. *IEEE Micro*,
         42(5).  <https://doi.org/10.1109/MM.2022.3186547>.

         Adel Ejjeh, Leon Medvinsky, **Aaron Councilman**, Hemanh Nehra,
         Suraj Sharma, Vikram Adve, Luigi Nardi, Eriko Nurvitadhi, and Rob
         Rutenbar.  2022. *HPVM2FPGA: Enabling True Hardware-Agnostic FPGA
         Programming*.  *Proceedings of the IEEE International Conference on
         Application-Specific Systems, Architectures, and Processors
         (ASAP)*.  <https://doi.org/10.1109/ASAP54787.2022.00012>.

     - layout: top-middle
       title: Extensible Implementation-Agnostic Parallel Programming
       caption: 2021
       link: github.com/melt-umn/ableC-parallel
       description: |
        Aaron Councilman. 2021. *An Extensible Implementation-Agnostic Parallel
        Programming Framework for C in ableC*. Bachelor's Thesis. University
        of Minnesota, Minneapolis, MN. <https://hdl.handle.net/11299/220246>.

     - layout: top-middle
       title: Extensible Parallel Programming
       caption: 2019
       description: |
        Aaron Councilman. 2019. *Extensible Parallel Programming in ableC*.
        Technical Report. University of Minnesota, Minneapolis, MN.
        <https://hdl.handle.net/11299/203190>.

     - layout: top-middle
       title: A Tensor Algebra Compiler as a Language Extension
       caption: 2018
       link: github.com/melt-umn/ableC-tensor-algebra
       description: |
        Travis Carlson, Ciaradh Coomey, Aaron Councilman, Stephen Patrick, and
        Eric Van Wyk. 2019. *An Investigation of Composable Language Extensions
        for Parallel Programming*. Department of Computer Science and
        Engineering Technical Report 19-001. University of Minnesota,
        Minneapolis, MN. <https://hdl.handle.net/11299/216034>.


  - title: Teaching
    layout: list
    content:
     - layout: top-middle
       title: Compiler Construction
       caption: Graduate Teaching Assistant, 2022
       description: |
        Updated and modified old assignments and created new assignments for
        the course. Delivered five classes of lectures, coving topics related
        to Global Dataflow Analysis.

     - layout: top-middle
       title: Introduction to Machine Architecture and Organization
       caption: Undergraduate Teaching Assistant, 2019

     - layout: top-middle
       title: Introduction to Algorithms and Data Structures
       caption: Undergraduate Teaching Assistant, 2018

  - title: Work Experience
    layout: list
    content:
     - layout: top-middle
       title: Software Development Engineer Intern
       sub_title: Amazon Music
       caption: 2020

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      In addition to my interests in computer science, some of my other interests and hobbies are:
      - Dancing (especially Jazz and Tap)
      - TTRPGs
      - [Cooking](https://recipe.acc240.com/)
      - Photography, for example
      
      ![Ferns](images/background-ferns.jpg "Ferns")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
